# -*- coding: utf-8 -*-
"""ICFES_Saber_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-h_uO6MD1Pc1K3Ia3o2UsSHH8KY7d7lp
"""

import pandas as pd

# Cargar el dataset
df = pd.read_csv('/content/Vista_Resultados_únicos_Saber_11_20260828.csv')

# Mostrar las primeras 5 filas del DataFrame
display(df.head())

!pip install ydata-profiling

from ydata_profiling import ProfileReport

# Generar el informe de perfilado
profile = ProfileReport(df, title="Reporte Inicial Perfilado")

# Guardar el informe como un archivo HTML
profile.to_file("Reporte Inicial Perfilado.html")

print("Informe de ydata_profiling generado y guardado como 'Reporte Inicial Perfilado.html'")

# Eliminar los registros duplicados del DataFrame
df_cleaned = df.drop_duplicates()

print(f"Dimensiones del DataFrame original: {df.shape}")
print(f"Dimensiones del DataFrame después de eliminar duplicados: {df_cleaned.shape}")

df = df_cleaned.copy()

columns_to_drop = [
    'PERIODO',
    'ESTU_TIPODOCUMENTO',
    'ESTU_CONSECUTIVO',
    'COLE_CALENDARIO',
    'COLE_CARACTER',
    'COLE_COD_DANE_ESTABLECIMIENTO',
    'COLE_COD_DANE_SEDE',
    'COLE_COD_DEPTO_UBICACION',
    'COLE_COD_MCPIO_UBICACION',
    'COLE_CODIGO_ICFES',
    'COLE_DEPTO_UBICACION',
    'COLE_GENERO',
    'COLE_NOMBRE_ESTABLECIMIENTO',
    'COLE_NOMBRE_SEDE',
    'COLE_SEDE_PRINCIPAL',
    'COLE_MCPIO_UBICACION',
    'ESTU_COD_DEPTO_PRESENTACION',
    'ESTU_COD_MCPIO_PRESENTACION',
    'ESTU_COD_RESIDE_DEPTO',
    'ESTU_COD_RESIDE_MCPIO',
    'ESTU_DEPTO_PRESENTACION',
    'ESTU_DEPTO_RESIDE',
    'ESTU_ESTADOINVESTIGACION',
    'ESTU_ESTUDIANTE',
    'ESTU_FECHANACIMIENTO',
    'ESTU_MCPIO_PRESENTACION',
    'ESTU_MCPIO_RESIDE',
    'ESTU_NACIONALIDAD',
    'ESTU_PAIS_RESIDE',
    'ESTU_PRIVADO_LIBERTAD',
    'FAMI_CUARTOSHOGAR',
    'FAMI_PERSONASHOGAR',
    'DESEMP_INGLES',
    'PUNT_INGLES',
    'PUNT_MATEMATICAS',
    'PUNT_SOCIALES_CIUDADANAS',
    'PUNT_C_NATURALES',
    'PUNT_LECTURA_CRITICA'
    ]

# Eliminar las columnas especificadas
df = df.drop(columns=columns_to_drop)

print(f"Dimensiones del DataFrame después de eliminar columnas: {df.shape}")

profile = ProfileReport(df, title="Reporte Perfilado Final")

# Guardar el informe como un archivo HTML
profile.to_file("Reporte Final Perfilado Final.html")

# La variable objetivo no debe imputarse en los valores nulos, por lo que procedo a eliminar los registros nulos
df = df.dropna(subset=['PUNT_GLOBAL'])
print(f"Dimensiones del DataFrame después de eliminar registros con 'PUNT_GLOBAL' nulo: {df.shape}")

df.info()

# Imputar nulos en variables de entrada categóricas con la moda
columns_to_fill_mode = [
    'COLE_BILINGUE',
    'ESTU_GENERO',
    'FAMI_EDUCACIONMADRE',
    'FAMI_EDUCACIONPADRE',
    'FAMI_ESTRATOVIVIENDA',
    'FAMI_TIENEAUTOMOVIL',
    'FAMI_TIENECOMPUTADOR',
    'FAMI_TIENEINTERNET',
    'FAMI_TIENELAVADORA'
]

for col in columns_to_fill_mode:
    if col in df.columns:
        mode_value = df[col].mode()[0]
        df[col].fillna(mode_value, inplace=True)
        print(f"Column '{col}': Missing values filled with mode '{mode_value}'")
    else:
        print(f"Column '{col}' not found in DataFrame.")

# Verify that there are no more missing values in the specified columns
print("\nMissing values after filling with mode:")
for col in columns_to_fill_mode:
    if col in df.columns:
        print(f"'{col}': {df[col].isnull().sum()} missing values")

df.info()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['PUNT_GLOBAL'], bins=30, kde=True, color='skyblue')
plt.title('Distribución de PUNT_GLOBAL')
plt.xlabel('Puntaje Global')
plt.ylabel('Frecuencia')
plt.grid(axis='y', alpha=0.75)
plt.show()

from sklearn.preprocessing import OneHotEncoder
import joblib

# Separar las variables de entrada (X) y la variable objetivo (y)
X = df.drop(columns=['PUNT_GLOBAL'])
y = df['PUNT_GLOBAL']

# Identificar automáticamente las columnas categóricas
categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
numeric_cols = X.select_dtypes(exclude=['object', 'category']).columns.tolist()

print(f"Columnas a codificar con OneHotEncoder: {categorical_cols}")

# Inicializar el OneHotEncoder
# Nota: usa sparse_output=False para sklearn >= 1.2 (o sparse=False para versiones anteriores)
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Ajustar y transformar los datos categóricos
encoded_array = encoder.fit_transform(X[categorical_cols])

# Convertir el arreglo resultante de vuelta a un DataFrame con los nombres correctos de las columnas
encoded_feature_names = encoder.get_feature_names_out(categorical_cols)
X_encoded_categorical = pd.DataFrame(encoded_array, columns=encoded_feature_names, index=X.index)

# Reconstruir el DataFrame uniendo las numéricas originales con las nuevas variables codificadas
X_final = pd.concat([X[numeric_cols], X_encoded_categorical], axis=1)

print(f"Dimensiones de X antes de codificar: {X.shape}")
print(f"Dimensiones de X_final después de codificar: {X_final.shape}")

# Serializar (guardar) el encoder con joblib
joblib.dump(encoder, 'one_hot_encoder.joblib')
print("Encoder serializado y guardado exitosamente como 'one_hot_encoder.joblib'")

display(X_final.head())

"""# División 70/30"""

from sklearn.model_selection import train_test_split

# Dividir los datos en conjuntos de entrenamiento y prueba (70-30)
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.3, random_state=42)

print(f"Dimensiones de X_train: {X_train.shape}")
print(f"Dimensiones de X_test: {X_test.shape}")
print(f"Dimensiones de y_train: {y_train.shape}")
print(f"Dimensiones de y_test: {y_test.shape}")

"""# Modelo KNN"""

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Inicializar el modelo KNN
# Se puede experimentar con diferentes valores de n_neighbors
knn_model = KNeighborsRegressor(n_neighbors=5)

# Entrenar el modelo con los datos de entrenamiento
knn_model.fit(X_train, y_train)

print("Modelo KNN entrenado exitosamente.")

# Realizar predicciones en el conjunto de prueba
y_pred_knn = knn_model.predict(X_test)

# Evaluar el rendimiento del modelo
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = mse_knn**0.5 # Root Mean Squared Error
r2_knn = r2_score(y_test, y_pred_knn)

print(f"Evaluación del modelo K-Nearest Neighbors:")
print(f"  Mean Absolute Error (MAE): {mae_knn:.2f}")
print(f"  Mean Squared Error (MSE): {mse_knn:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_knn:.2f}")
print(f"  R-squared (R2): {r2_knn:.2f}")

from sklearn.model_selection import GridSearchCV

# Definir el rango de hiperparámetros a buscar
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 13, 50, 100, 200]
}

# Inicializar GridSearchCV
# cv=5 indica 5-fold cross-validation
# scoring='neg_mean_squared_error' para optimizar el MSE (GridSearchCV busca maximizar, así que usamos el negativo)
grid_search_knn = GridSearchCV(KNeighborsRegressor(), param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Ejecutar la búsqueda en cuadrícula en los datos de entrenamiento
grid_search_knn.fit(X_train, y_train)

print("Mejores hiperparámetros encontrados:", grid_search_knn.best_params_)
print("Mejor score MSE (negativo):", grid_search_knn.best_score_)

# Evaluar el mejor modelo KNN encontrado por GridSearchCV
best_knn_model = grid_search_knn.best_estimator_
y_pred_best_knn = best_knn_model.predict(X_test)

mae_best_knn = mean_absolute_error(y_test, y_pred_best_knn)
mse_best_knn = mean_squared_error(y_test, y_pred_best_knn)
rmse_best_knn = mse_best_knn**0.5
r2_best_knn = r2_score(y_test, y_pred_best_knn)

print(f"Evaluación del mejor modelo K-Nearest Neighbors (después de GridSearchCV):")
print(f"  Mean Absolute Error (MAE): {mae_best_knn:.2f}")
print(f"  Mean Squared Error (MSE): {mse_best_knn:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_best_knn:.2f}")
print(f"  R-squared (R2): {r2_best_knn:.2f}")

"""# Red Neuronal"""

from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Inicializar el modelo MLPRegressor (Red Neuronal de scikit-learn) sin escalado
# Se usarán los datos X_train y X_test directamente, que ya están One-Hot Encoded
mlp_model_unscaled = MLPRegressor(
    hidden_layer_sizes=(100, 50), # Dos capas ocultas con 100 y 50 neuronas
    activation='relu', # Función de activación ReLU
    solver='adam', # Optimizador Adam
    max_iter=500, # Número máximo de iteraciones (épocas)
    random_state=42,
    verbose=True # Para ver el progreso del entrenamiento
)

print("Iniciando entrenamiento del modelo MLPRegressor (sin escalado)...")
# Entrenar el modelo con los datos de entrenamiento (One-Hot Encoded pero no escalados)
mlp_model_unscaled.fit(X_train, y_train)

print("Entrenamiento del modelo MLPRegressor (sin escalado) completado.")

# Realizar predicciones en el conjunto de prueba
y_pred_mlp_unscaled = mlp_model_unscaled.predict(X_test)

# Evaluar el rendimiento del modelo
mae_mlp_unscaled = mean_absolute_error(y_test, y_pred_mlp_unscaled)
mse_mlp_unscaled = mean_squared_error(y_test, y_pred_mlp_unscaled)
rmse_mlp_unscaled = mse_mlp_unscaled**0.5
r2_mlp_unscaled = r2_score(y_test, y_pred_mlp_unscaled)

print(f"Evaluación del modelo MLPRegressor (sin escalado):")
print(f"  Mean Absolute Error (MAE): {mae_mlp_unscaled:.2f}")
print(f"  Mean Squared Error (MSE): {mse_mlp_unscaled:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_mlp_unscaled:.2f}")
print(f"  R-squared (R2): {r2_mlp_unscaled:.2f}")

from sklearn.model_selection import GridSearchCV

# Definir el rango de hiperparámetros a buscar para MLPRegressor
param_grid_mlp_unscaled = {
    'hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 50)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam'],
    'max_iter': [1000, 1500] # Aumentar el número de iteraciones para favorecer la convergencia
}

# Inicializar GridSearchCV para MLPRegressor sin escalado
grid_search_mlp_unscaled = GridSearchCV(
    MLPRegressor(random_state=42, verbose=False), # Establecer verbose=False para no imprimir el progreso de cada modelo en la búsqueda
    param_grid_mlp_unscaled,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1
)

print("Iniciando la búsqueda de hiperparámetros para MLPRegressor (sin escalado) con GridSearchCV...")
# Ejecutar la búsqueda en cuadrícula en los datos de entrenamiento (sin escalado)
grid_search_mlp_unscaled.fit(X_train, y_train)

print("Búsqueda de hiperparámetros completada.")
print("Mejores hiperparámetros encontrados para MLPRegressor (sin escalado):", grid_search_mlp_unscaled.best_params_)
print("Mejor score MSE (negativo) para MLPRegressor (sin escalado):", grid_search_mlp_unscaled.best_score_)

# Evaluar el mejor modelo MLPRegressor encontrado por GridSearchCV (sin escalado)
best_mlp_model_unscaled = grid_search_mlp_unscaled.best_estimator_
y_pred_best_mlp_unscaled = best_mlp_model_unscaled.predict(X_test)

mae_best_mlp_unscaled = mean_absolute_error(y_test, y_pred_best_mlp_unscaled)
mse_best_mlp_unscaled = mean_squared_error(y_test, y_pred_best_mlp_unscaled)
rmse_best_mlp_unscaled = mse_best_mlp_unscaled**0.5
r2_best_mlp_unscaled = r2_score(y_test, y_pred_best_mlp_unscaled)

print(f"Evaluación del mejor modelo MLPRegressor (sin escalado, después de GridSearchCV):")
print(f"  Mean Absolute Error (MAE): {mae_best_mlp_unscaled:.2f}")
print(f"  Mean Squared Error (MSE): {mse_best_mlp_unscaled:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_best_mlp_unscaled:.2f}")
print(f"  R-squared (R2): {r2_best_mlp_unscaled:.2f}")

"""# Árbol de regresión"""

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Inicializar el modelo de Árbol de Regresión
dtr_model = DecisionTreeRegressor(random_state=42)

print("Iniciando entrenamiento del modelo de Árbol de Regresión...")
# Entrenar el modelo
dtr_model.fit(X_train, y_train)

print("Entrenamiento del modelo de Árbol de Regresión completado.")

# Realizar predicciones en el conjunto de prueba
y_pred_dtr = dtr_model.predict(X_test)

# Evaluar el rendimiento del modelo
mae_dtr = mean_absolute_error(y_test, y_pred_dtr)
mse_dtr = mean_squared_error(y_test, y_pred_dtr)
rmse_dtr = mse_dtr**0.5
r2_dtr = r2_score(y_test, y_pred_dtr)

print(f"Evaluación del modelo de Árbol de Regresión (sin ajuste):")
print(f"  Mean Absolute Error (MAE): {mae_dtr:.2f}")
print(f"  Mean Squared Error (MSE): {mse_dtr:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_dtr:.2f}")
print(f"  R-squared (R2): {r2_dtr:.2f}")

from sklearn.model_selection import GridSearchCV

# Definir el rango de hiperparámetros a buscar para DecisionTreeRegressor
param_grid_dtr = {
    'max_depth': [None, 10, 20, 30, 40, 50],
    'min_samples_split': [2, 5, 10, 15, 30],
    'min_samples_leaf': [1, 2, 4, 10]
}

# Inicializar GridSearchCV para DecisionTreeRegressor
grid_search_dtr = GridSearchCV(
    DecisionTreeRegressor(random_state=42),
    param_grid_dtr,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1
)

print("Iniciando la búsqueda de hiperparámetros para DecisionTreeRegressor con GridSearchCV...")
# Ejecutar la búsqueda en cuadrícula en los datos de entrenamiento
grid_search_dtr.fit(X_train, y_train)

print("Búsqueda de hiperparámetros completada.")
print("Mejores hiperparámetros encontrados para DecisionTreeRegressor:", grid_search_dtr.best_params_)
print("Mejor score MSE (negativo) para DecisionTreeRegressor:", grid_search_dtr.best_score_)

# Evaluar el mejor modelo DecisionTreeRegressor encontrado por GridSearchCV
best_dtr_model = grid_search_dtr.best_estimator_
y_pred_best_dtr = best_dtr_model.predict(X_test)

mae_best_dtr = mean_absolute_error(y_test, y_pred_best_dtr)
mse_best_dtr = mean_squared_error(y_test, y_pred_best_dtr)
rmse_best_dtr = mse_best_dtr**0.5
r2_best_dtr = r2_score(y_test, y_pred_best_dtr)

print(f"Evaluación del mejor modelo DecisionTreeRegressor (después de GridSearchCV):")
print(f"  Mean Absolute Error (MAE): {mae_best_dtr:.2f}")
print(f"  Mean Squared Error (MSE): {mse_best_dtr:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_best_dtr:.2f}")
print(f"  R-squared (R2): {r2_best_dtr:.2f}")

"""# Máquina de Soporte"""

from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Inicializar el modelo SVR
# Nota: SVR es sensible a la escala de las características. Aquí usaremos los datos sin escalar
# como se ha hecho con los modelos anteriores, aunque para SVR el escalado suele ser muy beneficioso.
svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1) # Kernel RBF con valores por defecto

print("Iniciando entrenamiento del modelo SVR...")
# Entrenar el modelo con los datos de entrenamiento (sin escalar)
svr_model.fit(X_train, y_train)

print("Entrenamiento del modelo SVR completado.")

# Realizar predicciones en el conjunto de prueba
y_pred_svr = svr_model.predict(X_test)

# Evaluar el rendimiento del modelo
mae_svr = mean_absolute_error(y_test, y_pred_svr)
mse_svr = mean_squared_error(y_test, y_pred_svr)
rmse_svr = mse_svr**0.5
r2_svr = r2_score(y_test, y_pred_svr)

print(f"Evaluación del modelo SVR (sin ajuste):")
print(f"  Mean Absolute Error (MAE): {mae_svr:.2f}")
print(f"  Mean Squared Error (MSE): {mse_svr:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_svr:.2f}")
print(f"  R-squared (R2): {r2_svr:.2f}")

from sklearn.model_selection import GridSearchCV

# Definir el rango de hiperparámetros a buscar para SVR
# Se usa un rango limitado debido al alto costo computacional de SVR
param_grid_svr = {
    'kernel': ['rbf'], # Se puede añadir 'linear', 'poly' pero aumenta mucho el tiempo de cómputo
    'C': [0.1, 1, 10],
    'epsilon': [0.01, 0.1, 0.5]
}

# Inicializar GridSearchCV para SVR
grid_search_svr = GridSearchCV(
    SVR(),
    param_grid_svr,
    cv=3, # Se reduce el número de folds para acelerar la búsqueda
    scoring='neg_mean_squared_error',
    n_jobs=-1
)

print("Iniciando la búsqueda de hiperparámetros para SVR con GridSearchCV... Esto puede tardar bastante.")
# Ejecutar la búsqueda en cuadrícula en los datos de entrenamiento
grid_search_svr.fit(X_train, y_train)

print("Búsqueda de hiperparámetros completada.")
print("Mejores hiperparámetros encontrados para SVR:", grid_search_svr.best_params_)
print("Mejor score MSE (negativo) para SVR:", grid_search_svr.best_score_)

# Evaluar el mejor modelo SVR encontrado por GridSearchCV
best_svr_model = grid_search_svr.best_estimator_
y_pred_best_svr = best_svr_model.predict(X_test)

mae_best_svr = mean_absolute_error(y_test, y_pred_best_svr)
mse_best_svr = mean_squared_error(y_test, y_pred_best_svr)
rmse_best_svr = mse_best_svr**0.5
r2_best_svr = r2_score(y_test, y_pred_best_svr)

print(f"Evaluación del mejor modelo SVR (después de GridSearchCV):")
print(f"  Mean Absolute Error (MAE): {mae_best_svr:.2f}")
print(f"  Mean Squared Error (MSE): {mse_best_svr:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_best_svr:.2f}")
print(f"  R-squared (R2): {r2_best_svr:.2f}")

"""# Regresión Lineal"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Inicializar el modelo de Regresión Lineal
linear_model = LinearRegression()

print("Iniciando entrenamiento del modelo de Regresión Lineal...")
# Entrenar el modelo con los datos de entrenamiento
linear_model.fit(X_train, y_train)

print("Entrenamiento del modelo de Regresión Lineal completado.")

# Realizar predicciones en el conjunto de prueba
y_pred_linear = linear_model.predict(X_test)

# Evaluar el rendimiento del modelo
mae_linear = mean_absolute_error(y_test, y_pred_linear)
mse_linear = mean_squared_error(y_test, y_pred_linear)
rmse_linear = mse_linear**0.5
r2_linear = r2_score(y_test, y_pred_linear)

print(f"Evaluación del modelo de Regresión Lineal (sin ajuste):")
print(f"  Mean Absolute Error (MAE): {mae_linear:.2f}")
print(f"  Mean Squared Error (MSE): {mse_linear:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_linear:.2f}")
print(f"  R-squared (R2): {r2_linear:.2f}")

from sklearn.model_selection import GridSearchCV

# Definir el rango de hiperparámetros a buscar para LinearRegression
# LinearRegression tiene pocos hiperparámetros que ajustar, pero podemos probar algunos.
param_grid_linear = {
    'fit_intercept': [True, False], # Si el intercepto debe ser calculado o no
    'copy_X': [True, False] # Si los datos X serán copiados o sobrescritos
}

# Inicializar GridSearchCV para LinearRegression
grid_search_linear = GridSearchCV(
    LinearRegression(),
    param_grid_linear,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1
)

print("Iniciando la búsqueda de hiperparámetros para Regresión Lineal con GridSearchCV...")
# Ejecutar la búsqueda en cuadrícula en los datos de entrenamiento
grid_search_linear.fit(X_train, y_train)

print("Búsqueda de hiperparámetros completada.")
print("Mejores hiperparámetros encontrados para Regresión Lineal:", grid_search_linear.best_params_)
print("Mejor score MSE (negativo) para Regresión Lineal:", grid_search_linear.best_score_)

# Evaluar el mejor modelo de Regresión Lineal encontrado por GridSearchCV
best_linear_model = grid_search_linear.best_estimator_
y_pred_best_linear = best_linear_model.predict(X_test)

mae_best_linear = mean_absolute_error(y_test, y_pred_best_linear)
mse_best_linear = mean_squared_error(y_test, y_pred_best_linear)
rmse_best_linear = mse_best_linear**0.5
r2_best_linear = r2_score(y_test, y_pred_best_linear)

print(f"Evaluación del mejor modelo de Regresión Lineal (después de GridSearchCV):")
print(f"  Mean Absolute Error (MAE): {mae_best_linear:.2f}")
print(f"  Mean Squared Error (MSE): {mse_best_linear:.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_best_linear:.2f}")
print(f"  R-squared (R2): {r2_best_linear:.2f}")

"""El mejor modelo es KNN"""

import joblib

# Serializar (guardar) el mejor modelo KNN
joblib.dump(best_knn_model, 'best_knn_model.joblib')

print("El mejor modelo KNN ha sido serializado y guardado como 'best_knn_model.joblib'")

app_py_content = """
import streamlit as st
import pandas as pd
import joblib
from sklearn.preprocessing import OneHotEncoder
# Ensure KNeighborsRegressor is imported as it's part of the loaded model's dependency
from sklearn.neighbors import KNeighborsRegressor


# Load the trained model and the OneHotEncoder
try:
    best_knn_model = joblib.load('best_knn_model.joblib')
    encoder = joblib.load('one_hot_encoder.joblib')
    # st.success("Modelo y codificador cargados exitosamente.") # Commented out for cleaner app UI
except Exception as e:
    st.error(f"Error al cargar el modelo o el codificador: {e}")
    st.stop()

# Define the original categorical column names (these were used to fit the encoder)
original_categorical_feature_names = [
    'COLE_AREA_UBICACION', 'COLE_BILINGUE', 'COLE_JORNADA', 'COLE_NATURALEZA',
    'ESTU_GENERO', 'FAMI_EDUCACIONMADRE', 'FAMI_EDUCACIONPADRE',
    'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEAUTOMOVIL', 'FAMI_TIENECOMPUTADOR',
    'FAMI_TIENEINTERNET', 'FAMI_TIENELAVADORA'
]

# Streamlit App Title
st.title("Predicción de Puntaje Global Saber 11")
st.write("Selecciona las características para predecir el puntaje global:")

# Dictionary to store user inputs
user_inputs = {}

# Create select boxes for each categorical variable
for i, col_name in enumerate(original_categorical_feature_names):
    if i < len(encoder.categories_):
        categories = encoder.categories_[i].tolist()
        user_inputs[col_name] = st.selectbox(f"**{col_name.replace('_', ' ')}**", categories)
    else:
        st.warning(f"No se encontraron categorías para la columna {col_name}. Verifique la configuración del codificador.")

if st.button("Predecir Puntaje Global"):
    # Create a DataFrame from user inputs. Ensure column order matches the encoder's expectation.
    input_data = {col: [user_inputs[col]] for col in original_categorical_feature_names}
    input_df = pd.DataFrame(input_data)

    try:
        # Transform the input using the loaded encoder
        encoded_input_array = encoder.transform(input_df)

        # Create a DataFrame with the encoded features, ensuring column names match the training data (X_final)
        encoded_feature_names = encoder.get_feature_names_out(original_categorical_feature_names)
        input_encoded = pd.DataFrame(encoded_input_array, columns=encoded_feature_names)

        # Make prediction
        prediction = best_knn_model.predict(input_encoded)[0]

        st.success(f"El puntaje global predicho es: **{prediction:.2f}**")
    except Exception as e:
        st.error(f"Error al realizar la predicción: {e}")
        st.write("Asegúrate de que todas las selecciones son válidas y que el codificador se aplicó correctamente.")
"""

with open('app.py', 'w') as f:
    f.write(app_py_content)

print("app.py generado exitosamente.")

# Code for requirements.txt
import pkg_resources

required_packages = ['streamlit', 'pandas', 'scikit-learn', 'joblib']
requirements_content = []

for pkg in required_packages:
    try:
        version = pkg_resources.get_distribution(pkg).version
        requirements_content.append(f"{pkg}=={version}")
    except pkg_resources.DistributionNotFound:
        requirements_content.append(f"{pkg} # Version not found in environment, please specify manually if needed")

with open('requirements.txt', 'w') as f:
    for line in requirements_content:
        f.write(line + '\n')

print("requirements.txt generado exitosamente.")